name: smsend
services:
  api:
    container_name: smsend_api
    depends_on:
      - db
    build: .
    ports:
      - '80:8080'
    env_file: .env
    environment:
      - NODE_ENV=production
  db:
    container_name: ${DB_HOST}
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db_pg_data:/etc/smsend/db_pg_data
volumes:
  db_pg_data:
    name: smsend_pg_db_data
